/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KuButton {
        "color": 'primary' | 'secondary' | 'accent';
        "disabled": boolean;
        "fluid": boolean;
        "href": string;
        "loading": boolean;
        "rounded": boolean;
        "type": 'button' | 'submit';
        "variant": 'ghost' | 'raised' | 'outline' | 'flat';
    }
    interface KuForm {
        "name": string;
        "novalidate": boolean;
    }
    interface KuInput {
        "classes": string;
        "defaultValue": string;
        "placeholder": string;
        "required": boolean;
        "type": 'text' | 'password' | 'email';
        "value": string;
        "variant": 'floated' | 'rounded';
    }
    interface KuSelect {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLKuButtonElement extends Components.KuButton, HTMLStencilElement {
    }
    var HTMLKuButtonElement: {
        prototype: HTMLKuButtonElement;
        new (): HTMLKuButtonElement;
    };
    interface HTMLKuFormElement extends Components.KuForm, HTMLStencilElement {
    }
    var HTMLKuFormElement: {
        prototype: HTMLKuFormElement;
        new (): HTMLKuFormElement;
    };
    interface HTMLKuInputElement extends Components.KuInput, HTMLStencilElement {
    }
    var HTMLKuInputElement: {
        prototype: HTMLKuInputElement;
        new (): HTMLKuInputElement;
    };
    interface HTMLKuSelectElement extends Components.KuSelect, HTMLStencilElement {
    }
    var HTMLKuSelectElement: {
        prototype: HTMLKuSelectElement;
        new (): HTMLKuSelectElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ku-button": HTMLKuButtonElement;
        "ku-form": HTMLKuFormElement;
        "ku-input": HTMLKuInputElement;
        "ku-select": HTMLKuSelectElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KuButton {
        "color"?: 'primary' | 'secondary' | 'accent';
        "disabled"?: boolean;
        "fluid"?: boolean;
        "href"?: string;
        "loading"?: boolean;
        "rounded"?: boolean;
        "type"?: 'button' | 'submit';
        "variant"?: 'ghost' | 'raised' | 'outline' | 'flat';
    }
    interface KuForm {
        "name"?: string;
        "novalidate"?: boolean;
    }
    interface KuInput {
        "classes"?: string;
        "defaultValue"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: 'text' | 'password' | 'email';
        "value"?: string;
        "variant"?: 'floated' | 'rounded';
    }
    interface KuSelect {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ku-button": KuButton;
        "ku-form": KuForm;
        "ku-input": KuInput;
        "ku-select": KuSelect;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ku-button": LocalJSX.KuButton & JSXBase.HTMLAttributes<HTMLKuButtonElement>;
            "ku-form": LocalJSX.KuForm & JSXBase.HTMLAttributes<HTMLKuFormElement>;
            "ku-input": LocalJSX.KuInput & JSXBase.HTMLAttributes<HTMLKuInputElement>;
            "ku-select": LocalJSX.KuSelect & JSXBase.HTMLAttributes<HTMLKuSelectElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
