/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KuAlert {
        "closable": boolean;
        "duration": number;
        "hide": () => Promise<void>;
        "msg": string;
        "open": boolean;
        "show": () => Promise<void>;
        "toast": () => Promise<void>;
        "variant": 'primary' | 'secondary' | 'accent' | 'success' | 'alert' | 'error';
    }
    interface KuAvatar {
        "height": string;
        "icon": string;
        /**
          * First letter of first and last name
         */
        "initials": any;
        "shape": 'circle' | 'rounded' | 'square';
        "src": any;
        "width": string;
    }
    interface KuButton {
        "color": 'primary' | 'secondary' | 'accent';
        "disabled": boolean;
        "fluid": boolean;
        "href": string;
        "loading": boolean;
        "rounded": boolean;
        "type": 'button' | 'submit';
        "variant": 'ghost' | 'raised' | 'outline' | 'flat';
    }
    interface KuForm {
        "name": string;
        "novalidate": boolean;
    }
    interface KuIcon {
        "name": string;
    }
    interface KuInput {
        "classes": string;
        "defaultValue": string;
        "placeholder": string;
        "required": boolean;
        "type": 'text' | 'password' | 'email';
        "value": string;
        "variant": 'legacy' | 'floated' | 'rounded';
    }
    interface KuSelect {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLKuAlertElement extends Components.KuAlert, HTMLStencilElement {
    }
    var HTMLKuAlertElement: {
        prototype: HTMLKuAlertElement;
        new (): HTMLKuAlertElement;
    };
    interface HTMLKuAvatarElement extends Components.KuAvatar, HTMLStencilElement {
    }
    var HTMLKuAvatarElement: {
        prototype: HTMLKuAvatarElement;
        new (): HTMLKuAvatarElement;
    };
    interface HTMLKuButtonElement extends Components.KuButton, HTMLStencilElement {
    }
    var HTMLKuButtonElement: {
        prototype: HTMLKuButtonElement;
        new (): HTMLKuButtonElement;
    };
    interface HTMLKuFormElement extends Components.KuForm, HTMLStencilElement {
    }
    var HTMLKuFormElement: {
        prototype: HTMLKuFormElement;
        new (): HTMLKuFormElement;
    };
    interface HTMLKuIconElement extends Components.KuIcon, HTMLStencilElement {
    }
    var HTMLKuIconElement: {
        prototype: HTMLKuIconElement;
        new (): HTMLKuIconElement;
    };
    interface HTMLKuInputElement extends Components.KuInput, HTMLStencilElement {
    }
    var HTMLKuInputElement: {
        prototype: HTMLKuInputElement;
        new (): HTMLKuInputElement;
    };
    interface HTMLKuSelectElement extends Components.KuSelect, HTMLStencilElement {
    }
    var HTMLKuSelectElement: {
        prototype: HTMLKuSelectElement;
        new (): HTMLKuSelectElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ku-alert": HTMLKuAlertElement;
        "ku-avatar": HTMLKuAvatarElement;
        "ku-button": HTMLKuButtonElement;
        "ku-form": HTMLKuFormElement;
        "ku-icon": HTMLKuIconElement;
        "ku-input": HTMLKuInputElement;
        "ku-select": HTMLKuSelectElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KuAlert {
        "closable"?: boolean;
        "duration"?: number;
        "msg"?: string;
        "onAlert.hidden"?: (event: CustomEvent<void>) => void;
        "onAlert.hide"?: (event: CustomEvent<void>) => void;
        "onAlert.show"?: (event: CustomEvent<void>) => void;
        "onAlert.shown"?: (event: CustomEvent<void>) => void;
        "open"?: boolean;
        "variant"?: 'primary' | 'secondary' | 'accent' | 'success' | 'alert' | 'error';
    }
    interface KuAvatar {
        "height"?: string;
        "icon"?: string;
        /**
          * First letter of first and last name
         */
        "initials"?: any;
        "shape"?: 'circle' | 'rounded' | 'square';
        "src"?: any;
        "width"?: string;
    }
    interface KuButton {
        "color"?: 'primary' | 'secondary' | 'accent';
        "disabled"?: boolean;
        "fluid"?: boolean;
        "href"?: string;
        "loading"?: boolean;
        "rounded"?: boolean;
        "type"?: 'button' | 'submit';
        "variant"?: 'ghost' | 'raised' | 'outline' | 'flat';
    }
    interface KuForm {
        "name"?: string;
        "novalidate"?: boolean;
    }
    interface KuIcon {
        "name"?: string;
    }
    interface KuInput {
        "classes"?: string;
        "defaultValue"?: string;
        "placeholder"?: string;
        "required"?: boolean;
        "type"?: 'text' | 'password' | 'email';
        "value"?: string;
        "variant"?: 'legacy' | 'floated' | 'rounded';
    }
    interface KuSelect {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ku-alert": KuAlert;
        "ku-avatar": KuAvatar;
        "ku-button": KuButton;
        "ku-form": KuForm;
        "ku-icon": KuIcon;
        "ku-input": KuInput;
        "ku-select": KuSelect;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ku-alert": LocalJSX.KuAlert & JSXBase.HTMLAttributes<HTMLKuAlertElement>;
            "ku-avatar": LocalJSX.KuAvatar & JSXBase.HTMLAttributes<HTMLKuAvatarElement>;
            "ku-button": LocalJSX.KuButton & JSXBase.HTMLAttributes<HTMLKuButtonElement>;
            "ku-form": LocalJSX.KuForm & JSXBase.HTMLAttributes<HTMLKuFormElement>;
            "ku-icon": LocalJSX.KuIcon & JSXBase.HTMLAttributes<HTMLKuIconElement>;
            "ku-input": LocalJSX.KuInput & JSXBase.HTMLAttributes<HTMLKuInputElement>;
            "ku-select": LocalJSX.KuSelect & JSXBase.HTMLAttributes<HTMLKuSelectElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
